# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160905_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/default.jpg', upload_to='blog/thumbnails/'),
        ),
    ]
